#!/usr/bin/env bash

# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

export BASE_DIR=$(pwd)
export REGION=us-central1

# Shared VPC Config
export NETWORK=cda-vpc
export SUBNET1=tier-1
export SUBNET2=tier-2
export SUBNET3=serverless-subnet

# IAP Setup used by iap/enable_iap.sh
export DISPLAY_NAME="cda-ui"
export IAP_SECRET_NAME="cda-iap-secret"
export SA_START_PIPELINE="serviceAccount:cloudrun-startpipeline-sa@${PROJECT_ID}.iam.gserviceaccount.com"
export SA_QUEUE="serviceAccount:cloudrun-queue-sa@${PROJECT_ID}.iam.gserviceaccount.com"
export APPLICATION_NAME="CDA Application"
export SA_GKE="gke-sa"
export SERVICE_ACCOUNT_EMAIL_GKE="${SA_GKE}@${PROJECT_ID}.iam.gserviceaccount.com"
export SA_DOCAI="service-${DOCAI_PROJECT_NUMBER}@gcp-sa-prod-dai-core.iam.gserviceaccount.com"

#Big Query
export BIGQUERY_DATASET=validation

# Terraform Variable
export TF_LOG_PATH="$BASE_DIR"/tf.log
#export TF_LOG="DEBUG"
export TF_VAR_api_domain=$API_DOMAIN
export TF_VAR_project_id=$PROJECT_ID
export TF_VAR_docai_project_id=${DOCAI_PROJECT_ID:-$PROJECT_ID}
export TF_BUCKET_NAME="${PROJECT_ID}-tfstate"
export TF_BUCKET_LOCATION="us"
export TF_VAR_config_bucket="${PROJECT_ID}-config"
export TF_VAR_region=$REGION
export TF_VAR_iap_secret_name="${IAP_SECRET_NAME}"
export TF_VAR_dataset_id="${BIGQUERY_DATASET}"
export TF_VAR_service_account_name_gke=${SA_GKE}

# used by Microservices
export CONFIG_BUCKET=${TF_VAR_config_bucket}
export DEBUG=True

export SKAFFOLD_DEFAULT_REPO="$REGION-docker.pkg.dev/$PROJECT_ID/gcr-artifacts"

#export DOCAI_WH_PROJECT_ID=${DOCAI_WH_PROJECT_ID:-$PROJECT_ID} Disabling DocAI WH
export DOCAI_WH_PROJECT_ID=$PROJECT_ID
export DOCAI_WH_PROJECT_NUMBER=$(gcloud projects describe  "${DOCAI_WH_PROJECT_ID}" --format='get(projectNumber)')
export SA_DOCAI_WH="service-${DOCAI_WH_PROJECT_NUMBER}@gcp-sa-cloud-cw.iam.gserviceaccount.com"

echo "Using       PROJECT_ID=$TF_VAR_project_id, CONFIG_BUCKET=$CONFIG_BUCKET, API_DOMAIN=$TF_VAR_api_domain"
echo "(Optional)  HOST_PROJECT_ID=$HOST_PROJECT_ID, DOCAI_PROJECT_ID=$TF_VAR_docai_project_id"
#echo "(Optional)  DOCAI_WH_PROJECT_ID=$DOCAI_WH_PROJECT_ID, DOCAI_WH_PROJECT_NUMBER=$DOCAI_WH_PROJECT_NUMBER"
