steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - '--build-arg'
  - 'BASE_IMG=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/common'
  - '-t'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE}:latest'
  - '--cache-from'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE}:latest'
  - '-f'
  - Dockerfile
  - .

- name: gcr.io/cloud-builders/docker
  args:
  - push
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE}'

images:
- '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE}:latest'